# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc-definition.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc-definition.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15grpc-definition.proto\x12\x18model.grpc.autogenerated\"M\n\x0cModelRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\x0c\n\x04size\x18\x03 \x01(\x03\x12\x0c\n\x04hash\x18\x04 \x01(\t\",\n\rModelResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2n\n\x0cModelService\x12^\n\x0bUploadModel\x12&.model.grpc.autogenerated.ModelRequest\x1a\'.model.grpc.autogenerated.ModelResponseB\x16Z\x14/autogenerated;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_definition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\024/autogenerated;proto'
  _globals['_MODELREQUEST']._serialized_start=51
  _globals['_MODELREQUEST']._serialized_end=128
  _globals['_MODELRESPONSE']._serialized_start=130
  _globals['_MODELRESPONSE']._serialized_end=174
  _globals['_MODELSERVICE']._serialized_start=176
  _globals['_MODELSERVICE']._serialized_end=286
# @@protoc_insertion_point(module_scope)
