[supervisord]
nodaemon=true

[program:go_grpc_server]
command=/usr/local/bin/flnode
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
autostart=true
autorestart=true

[program:python_grpc_server]
command=python3 /app/model/grpc/grpc-server.py
directory=/app
environment=PYTHONPATH="/app"
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
autostart=true
autorestart=true
