// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: grpc-definition.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Hash          string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelRequest) Reset() {
	*x = ModelRequest{}
	mi := &file_grpc_definition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelRequest) ProtoMessage() {}

func (x *ModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_definition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelRequest.ProtoReflect.Descriptor instead.
func (*ModelRequest) Descriptor() ([]byte, []int) {
	return file_grpc_definition_proto_rawDescGZIP(), []int{0}
}

func (x *ModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ModelRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ModelRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type ModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelResponse) Reset() {
	*x = ModelResponse{}
	mi := &file_grpc_definition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelResponse) ProtoMessage() {}

func (x *ModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_definition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelResponse.ProtoReflect.Descriptor instead.
func (*ModelResponse) Descriptor() ([]byte, []int) {
	return file_grpc_definition_proto_rawDescGZIP(), []int{1}
}

func (x *ModelResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_grpc_definition_proto protoreflect.FileDescriptor

const file_grpc_definition_proto_rawDesc = "" +
	"\n" +
	"\x15grpc-definition.proto\x12\tprotogrpc\"k\n" +
	"\fModelRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\"9\n" +
	"\rModelResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2P\n" +
	"\fModelService\x12@\n" +
	"\vUploadModel\x12\x17.protogrpc.ModelRequest\x1a\x18.protogrpc.ModelResponseB\x16Z\x14/autogenerated;protob\x06proto3"

var (
	file_grpc_definition_proto_rawDescOnce sync.Once
	file_grpc_definition_proto_rawDescData []byte
)

func file_grpc_definition_proto_rawDescGZIP() []byte {
	file_grpc_definition_proto_rawDescOnce.Do(func() {
		file_grpc_definition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_definition_proto_rawDesc), len(file_grpc_definition_proto_rawDesc)))
	})
	return file_grpc_definition_proto_rawDescData
}

var file_grpc_definition_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_definition_proto_goTypes = []any{
	(*ModelRequest)(nil),  // 0: protogrpc.ModelRequest
	(*ModelResponse)(nil), // 1: protogrpc.ModelResponse
}
var file_grpc_definition_proto_depIdxs = []int32{
	0, // 0: protogrpc.ModelService.UploadModel:input_type -> protogrpc.ModelRequest
	1, // 1: protogrpc.ModelService.UploadModel:output_type -> protogrpc.ModelResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_definition_proto_init() }
func file_grpc_definition_proto_init() {
	if File_grpc_definition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_definition_proto_rawDesc), len(file_grpc_definition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_definition_proto_goTypes,
		DependencyIndexes: file_grpc_definition_proto_depIdxs,
		MessageInfos:      file_grpc_definition_proto_msgTypes,
	}.Build()
	File_grpc_definition_proto = out.File
	file_grpc_definition_proto_goTypes = nil
	file_grpc_definition_proto_depIdxs = nil
}
