package grpc

import (
	"context"
	"log"
	"os"
	"path/filepath"
	"time"

	"github.com/bqnic/diplomski-projekt/common"
	pb "github.com/bqnic/diplomski-projekt/grpc/autogenerated"
	"github.com/bqnic/diplomski-projekt/pubsub"
)

type GoModelServer struct {
    pb.UnimplementedModelServiceServer
    SaveDir string
}

func mapModelRequestToModelMeta(req *pb.ModelRequest) common.ModelMeta {
    return common.ModelMeta{PeerID: common.Host.ID().String(), ModelID: req.ModelId, Size: req.Size, Time: time.Now().Unix(), Hash: req.Hash}
}

func (s *GoModelServer) UploadModel(ctx context.Context, req *pb.ModelRequest) (*pb.ModelResponse, error) {
    dst := filepath.Join(s.SaveDir, req.ModelId)

    err := os.WriteFile(dst, req.Content, 0644)
    if err != nil {
        return &pb.ModelResponse{Ok: false, Message: "Failed to save file"}, nil
    }

    log.Printf("Go server: received model %s (%d bytes)", req.ModelId, len(req.Content))
    
    pubsub.AnnounceModel(mapModelRequestToModelMeta(req))

    return &pb.ModelResponse{Ok: true, Message: "Model stored"}, nil
}

// Called by Go client to deliver model to Python
func (s *GoModelServer) DeliverModel(ctx context.Context, req *pb.ModelRequest) (*pb.ModelResponse, error) {
    log.Println("Go server DeliverModel called — normally Python is the receiver")
    return &pb.ModelResponse{Ok: true, Message: "Go server got deliver request"}, nil
}
