package grpc

import (
    "context"
    "os"
    "path/filepath"
    "time"

    "github.com/bqnic/diplomski-projekt/common"
    pb "github.com/bqnic/diplomski-projekt/grpc/autogenerated"
    "github.com/bqnic/diplomski-projekt/pubsub"
    "google.golang.org/grpc"
)

type GoModelServer struct {
    pb.UnimplementedModelServiceServer
    SaveDir string
}

func (s *GoModelServer) UploadModel(ctx context.Context, req *pb.ModelRequest) (*pb.ModelResponse, error) {
    dst := filepath.Join(s.SaveDir, req.ModelId)

    err := os.WriteFile(dst, req.Content, 0644)
    if err != nil {
        return &pb.ModelResponse{Ok: false, Message: "Failed to save file"}, nil
    }

    common.Log.Infow("Received model via gRPC", "model", req.ModelId, "size", len(req.Content))

    pubsub.AnnounceModel(mapModelRequestToModelMeta(req))

    return &pb.ModelResponse{Ok: true, Message: "Model stored"}, nil
}

func SetupGrpcServer() *grpc.Server {
    grpcServer := grpc.NewServer()
    pb.RegisterModelServiceServer(grpcServer, &GoModelServer{
        SaveDir: common.LocalModelDir,
    })

    common.Log.Infow("gRPC server listening", "addr", ":50051")

    return grpcServer
}

func mapModelRequestToModelMeta(req *pb.ModelRequest) common.ModelMeta {
    return common.ModelMeta{PeerID: common.Host.ID().String(), ModelID: req.ModelId, Size: req.Size, Time: time.Now().Unix(), Hash: req.Hash}
}