package grpc

import (
    "context"
    "os"
    "path/filepath"
    "time"

    "github.com/bqnic/diplomski-projekt/common"
    "google.golang.org/grpc"

    pb "github.com/bqnic/diplomski-projekt/grpc/autogenerated"
)

func SendToPython(address, filePath string) error {
    conn, err := grpc.Dial(address, grpc.WithInsecure())
    if err != nil {
        return err
    }
    defer conn.Close()

    client := pb.NewModelServiceClient(conn)

    content, err := os.ReadFile(filePath)
    if err != nil {
        return err
    }

    ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
    defer cancel()

    resp, err := client.UploadModel(ctx, &pb.ModelRequest{
        ModelId: filepath.Base(filePath),
        Content: content,
        Size:    int64(len(content)),
        Hash:    "",
    })
    if err != nil {
        return err
    }

    common.Log.Infow("Sent model to Python gRPC server", "response", resp.Message)
    return nil
}
