version: "3.9"

services:
    node:
        build: .
        command: >
            /app/main
            -listen /ip4/0.0.0.0/tcp/${LISTEN_PORT:-9000}
            -local /models
            -remote /models/remote-models
            -nick ${NICK:-node}
            ${EXTRA_ARGS:-}
        volumes:
            - ./models/${NICK:-node}:/models
        environment:
            - NICK=${NICK:-node}
            - LISTEN_PORT=${LISTEN_PORT:-9000}
            - EXTRA_ARGS=${EXTRA_ARGS:-}
