import grpc
from model.grpc.autogenerated.grpc_definition_pb2_grpc import ModelServiceStub
from model.grpc.autogenerated.grpc_definition_pb2 import ModelRequest

def send_model_to_peer(model_id: str, content_bytes: bytes, grpc_addr: str = "localhost:50051") -> str:
    """
    Send a trained model (zipped .weights.bin + .meta.json) to a Go peer via gRPC.

    Args:
        model_id: Unique identifier for the model/epoch.
        content_bytes: Zipped content of weights + meta.
        grpc_addr: Address of gRPC server.

    Returns:
        str: Response message from the Go peer.
    """

    # Open gRPC channel and stub
    channel = grpc.insecure_channel(grpc_addr)
    stub = ModelServiceStub(channel)

    # Send the model bytes
    resp = stub.UploadModel(ModelRequest(
        model_id=model_id,
        content=content_bytes,
        size=len(content_bytes),
        hash=""
    ))

    return resp.message
