import grpc

from model.grpc.autogenerated.grpc_definition_pb2_grpc import ModelServiceStub
from model.grpc.autogenerated.grpc_definition_pb2 import ModelRequest

def send_to_go(path, model_id):
    with open(path, "rb") as f:
        content = f.read()

    channel = grpc.insecure_channel("localhost:50051")
    stub = ModelServiceStub(channel)

    resp = stub.UploadModel(ModelRequest(
        model_id=model_id,
        content=content,
        size=len(content),
        hash=""
    ))

    print("Python client: Go replied:", resp.message)

def test():
    print("Sending message.")
    send_to_go("shared/yes.txt", "1")

    while True:
        # just chillin
        continue

if __name__ == "__main__":
    test()
