import grpc
import time
import os
import random
import string

from model.grpc.autogenerated.grpc_definition_pb2_grpc import ModelServiceStub
from model.grpc.autogenerated.grpc_definition_pb2 import ModelRequest

TEST_DIR = "test-files"

# Ensure the folder exists
os.makedirs(TEST_DIR, exist_ok=True)

def random_text(length=50):
    """Generate a random string of letters and digits."""
    letters = string.ascii_letters + string.digits
    return ''.join(random.choice(letters) for _ in range(length))

def generate_file(file_id):
    """Create a new file with random content."""
    filename = f"{TEST_DIR}/file_{file_id}.txt"
    content = random_text(random.randint(20, 200))  # random length
    with open(filename, "w") as f:
        f.write(content)
    return filename

def send_to_go(path, model_id):
    with open(path, "rb") as f:
        content = f.read()

    channel = grpc.insecure_channel("localhost:50051")
    stub = ModelServiceStub(channel)

    resp = stub.UploadModel(ModelRequest(
        model_id=model_id,
        content=content,
        size=len(content),
        hash=""
    ))

    print(f"Python client: Go replied for file {path}: {resp.message}")

def main_loop():
    file_counter = 1
    while True:
        filename = generate_file(file_counter)
        print(f"Generated file: {filename}")
        send_to_go(filename, str(file_counter))
        file_counter += 1
        time.sleep(15)  # wait 15 seconds before next file

if __name__ == "__main__":
    main_loop()
