import grpc
import io

from model.grpc.autogenerated.grpc_definition_pb2_grpc import ModelServiceStub
from model.grpc.autogenerated.grpc_definition_pb2 import ModelRequest

def send_model_to_peer(buffer: io.BytesIO, model_id: str, grpc_addr: str = "localhost:50051"):
    """
    Send the serialized model buffer (.pt with metadata) to a Go peer via gRPC.
    """
    channel = grpc.insecure_channel(grpc_addr)
    stub = ModelServiceStub(channel)
    
    # Prepare request
    content_bytes = buffer.getvalue()
    req = ModelRequest(
        model_id=model_id,
        content=content_bytes,
        size=len(content_bytes),
        hash=""
    )

    # Send
    resp = stub.UploadModel(req)
    return resp.message
